### ISSUE TITLE
[RECOMENDATION] Try Nix package manager!!!

### ISSUE THREAD

**Issue by danteay** [faabiosr/exegol#1]
Hi Fabio!!! Long time no see you!!!

This repo is very courious because I've been implemented something like this for my current company and it works too weel to reproduce environments!!! 

Give it a chance when you have time!!

https://gist.github.com/danteay/927f6505c7aa9779510486718ca631e9

**Comment by faabiosr** [comment]
Thank you so much for the tip (Muchas gracias)!
